INSERT INTO EsporteEG VALUES (ESPORTE_ID_ESPORTE_SEQ_1.NEXTVAL, 'Futebol', 'Pedro');
INSERT INTO EsporteEG VALUES (ESPORTE_ID_ESPORTE_SEQ_1.NEXTVAL, 'Basquete', 'Fernando');
INSERT INTO EsporteEG VALUES (ESPORTE_ID_ESPORTE_SEQ_1.NEXTVAL, 'Volei', 'Rafael');


INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Mauro', 5, 2);
INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Fabricio', 3, 3);
INSERT INTO ProfessoresEG VALUES (PROFESSOR_ID_PROFESSOR.NEXTVAL, 'Joao', 4, 1);


INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Maria', 12334567855, 3);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Gabriel', 23421127855, 2);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Marcos', 26354718294, 1);
INSERT INTO AlunosEG VALUES (ALUNOS_MATRICULA_SEQ.NEXTVAL, 'Carlos', 99988823465, 2);
